# 项目名称和描述
name: windows
description: "一个新的Flutter项目。"

# 发布设置
publish_to: 'none' # 不发布到 pub.dev

# 版本号
version: 1.0.0+1

# Dart SDK 版本要求
environment:
  sdk: '>=3.4.4 <4.0.0'

# 项目依赖
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6 # iOS风格图标
  shared_preferences: ^2.0.0 # 本地数据存储

# 开发依赖
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # 代码规范检查工具

# Flutter 相关配置
flutter:
  uses-material-design: true # 使用 Material Design

  # 资源文件配置
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # 字体配置
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
